name: Deploy on push

# Runs tests on any push in main
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    # Runs if commit is pushed to main
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            cd ${{ secrets.PROJECT_FOLDER }};
            git pull;
            docker compose build;
            docker compose down;
            docker compose up -d;
            docker exec docs_api alembic upgrade head;